version: '3.9'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234@abcd"
      MYSQL_DATABASE: synapse-accounts
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  auth:
    build:
      context: ./auth-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: auth-service
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy # Espera a que el healthcheck de la DB sea positivo
    environment:
      QUARKUS_DATASOURCE_DB_KIND: mysql
      # Importante: aquí usamos 'db' porque es el nombre del servicio en el compose
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/synapse-accounts
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      # Añadimos las rutas de las llaves que ya están dentro del JAR
      SMALLRYE_JWT_SIGN_KEY_LOCATION: SynapseAuthKey.pem
      SMALLRYE_JWT_VERIFY_KEY_LOCATION: publicSynapseAuthKey.pem
    volumes:
      - ./auth-service/src/main/resources/SynapseAuthKey.pem:/deployments/SynapseAuthKey.pem

volumes:
  db_data: