services:
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "1234@abcd"
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - synapse-net
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - synapse-net
    depends_on:
      - auth
      - catalog
  auth:
    build:
      context: ./auth-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: auth-service
    expose:
      - "8080"
    networks:
      - synapse-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_DB_KIND: mysql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/synapse-accounts
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      SMALLRYE_JWT_SIGN_KEY_LOCATION: SynapseAuthKey.pem
      SMALLRYE_JWT_VERIFY_KEY_LOCATION: publicSynapseAuthKey.pem
    volumes:
      - ./auth-service/src/main/resources/SynapseAuthKey.pem:/deployments/SynapseAuthKey.pem

  catalog:
    build:
      context: ./catalog-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: catalog-service
    expose:
      - "8080"
    networks:
      - synapse-net
    volumes:
      - ./manuals_storage:/deployments/uploads
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/synapse-catalog
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
  home:
    build:
      context: ./home-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: home-service
    expose:
      - "8080"
    networks:
      - synapse-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/synapse-home
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: synapse-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - synapse-network
  user:
    build:
      context: ./user-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: user-service
    expose:
      - "8080"
    networks:
      - synapse-net
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/synapse-home
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
volumes:
  db_data:

networks:
  synapse-net:
    driver: bridge