server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: auth-routes
            uri: http://localhost:8080
            predicates:
            - Path=/auth/**
          - id: catalog-service
            uri: http://localhost:8080
            predicates:
              - Path=/catalog/**
          - id: manual-service
            uri: http://localhost:8080
            predicates:
              - Path=/manuals/**
              