server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: auth-routes
            uri: http://auth-service:8080
            predicates:
            - Path=/auth/**

          - id: catalog-service
            uri: http://catalog-service:8080
            predicates:
              - Path=/catalog/**

          - id: manual-service
            uri: http://catalog-service:8080
            predicates:
              - Path=/manuals/**
          
          - id: home-service
            uri: http://home-service:8080
            predicates:
              - Path=/home/**
          - id: user-service
            uri: http://user-service:8080
            predicates:
            - Path=/user/**