server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000" # Web
              - "capacitor://localhost"      # App Móvil (iOS)
              - "http://localhost"           # App Móvil (Android / Web)
              - "ionic://localhost"          # App Móvil (Ionic)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webmvc:
          routes:
          - id: auth-routes
            uri: http://auth-service:8080
            predicates:
            - Path=/auth/**

          - id: catalog-service
            uri: http://catalog-service:8080
            predicates:
              - Path=/catalog/**

          - id: manual-service
            uri: http://catalog-service:8080
            predicates:
              - Path=/manuals/**
          
          - id: home-service
            uri: http://home-service:8080
            predicates:
              - Path=/home/**

          - id: user-service
            uri: http://user-service:8080
            predicates:
            - Path=/profiles/**

          - id: subscription-service
            uri: http://user-service:8080
            predicates:
            - Path=/subscriptions/**